### PR TITLE
new email texts

### PR DESCRIPTION
**Pull request by bumi**
@puneetbharill can you review them?  some are slightly changed from your initial text because we do not have all the information (like for example the name for the welcome email).

### CODE REVIEW

**Comment by bumi** [comment]
if it is fine, simply merge. :)

**Comment by puneetbharill** [comment]
I tried to read all the text in the code and it looks fine. I am gonna merge it but it is easier for me to just look at the emails and then suggest you changes based on typos or if something can be improved.

**Comment by bumi** [comment]
where do you have problems to read it? instead for `<%= .... %>` read tomato or salad. :)
let me know then we can go over it . the PR is ment for discussing the changes.

**Comment by puneetbharill** [comment]
Yes sure, I did as you mentioned. I read all of the material and I think it is ok :) Now I want to see how the emails look to see if we skipped something ;)

**Comment by kangguru** [comment]
:tomato:

**Comment by bumi** [comment]
@puneetbharill changes are online

**Pull request merged**
