### PR TITLE
added support for multiple recipients [resolves #13]

### LINKED ISSUE #13: support for multiple package recipients
It might be interesting to send the same photo package to multiple recipients. 
which would also mean we generate more packages :)

### PR DESCRIPTION
**Pull request by bumi**
This solves #13 and allows us to send one order to multiple recipients.

A group has many recipients, and after creating an order we request prints of the group's pictures for every recipient (recipient_order).

This is actually a big change to the quickly hacked kuvakehys app and because at least @paulkogel  requested this feature I think he should be the one to review it and merge this pull request. :D

### CODE REVIEW

**Comment by bumi** [comment]
@puneetbharill can you merge this PR (if you think the feature to support multiple recipients should make it online). 
Pull Requests quickly get old and start to stink... so they either need to be closed or merged. :)
thanks :cat2:

**Comment by bumi** [comment]
whoa. omg. hope it does not break anything :) 
congrats to you first code commit: 701377bc8b164879aea1f5244ef6b243ef7caf65

**Comment by bumi** [comment]
btw. shipping is the most important when writing code: :shipit: :ship:

**Comment by bumi** [comment]
done. it's :ship:ed @paulkogel :rocket:

**Comment by puneetbharill** [comment]
I remember....it's null till you ship it....right? haha....nice cartoons ;)

**Comment by bumi** [comment]
here some reading on the "cartoons": http://www.der-postillon.com/2015/11/bremen-ersetzt-als-erstes-bundesland.html

**Comment by puneetbharill** [comment]
hahaha awesome! I hope you already know about the oxford dictionary's word of 2015 :)

**Pull request merged**
